name: ORCLPDB1.LOCALDOMAIN
desc: ""
tables:
- name: OT.WAREHOUSES
  type: TABLE
  comment: ""
  columns:
  - name: LOCATION_ID
    type: NUMBER
    nullable: true
    default: null
    comment: ""
  - name: WAREHOUSE_NAME
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  - name: WAREHOUSE_ID
    type: NUMBER
    nullable: false
    default: "\"OT\".\"ISEQ$$_77191\".nextval"
    comment: ""
  indexes: []
  constraints:
  - name: SYS_C0010989
    type: PRIMARY KEY
    def: PRIMARY KEY (WAREHOUSE_ID)
    table: OT.WAREHOUSES
    referencedTable: ""
    columns:
    - WAREHOUSE_ID
    referencedColumns: []
    comment: ""
  - name: FK_WAREHOUSES_LOCATIONS
    type: FOREIGN KEY
    def: FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (LOCATION_ID)
    table: OT.WAREHOUSES
    referencedTable: LOCATIONS
    columns:
    - LOCATION_ID
    referencedColumns:
    - LOCATION_ID
    comment: ""
  triggers: []
  def: ""
- name: OT.ORDER_ITEMS
  type: TABLE
  comment: ""
  columns:
  - name: UNIT_PRICE
    type: NUMBER
    nullable: false
    default: null
    comment: ""
  - name: ORDER_ID
    type: NUMBER
    nullable: false
    default: null
    comment: ""
  - name: QUANTITY
    type: NUMBER
    nullable: false
    default: null
    comment: ""
  - name: ITEM_ID
    type: NUMBER
    nullable: false
    default: null
    comment: ""
  - name: PRODUCT_ID
    type: NUMBER
    nullable: false
    default: null
    comment: ""
  indexes: []
  constraints:
  - name: PK_ORDER_ITEMS
    type: PRIMARY KEY
    def: PRIMARY KEY (ITEM_ID, ORDER_ID)
    table: OT.ORDER_ITEMS
    referencedTable: ""
    columns:
    - ITEM_ID
    - ORDER_ID
    referencedColumns: []
    comment: ""
  - name: FK_ORDER_ITEMS_ORDERS
    type: FOREIGN KEY
    def: FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
    table: OT.ORDER_ITEMS
    referencedTable: ORDERS
    columns:
    - ORDER_ID
    referencedColumns:
    - ORDER_ID
    comment: ""
  - name: FK_ORDER_ITEMS_PRODUCTS
    type: FOREIGN KEY
    def: FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
    table: OT.ORDER_ITEMS
    referencedTable: PRODUCTS
    columns:
    - PRODUCT_ID
    referencedColumns:
    - PRODUCT_ID
    comment: ""
  triggers: []
  def: ""
- name: OT.PRODUCT_CATEGORIES
  type: TABLE
  comment: ""
  columns:
  - name: CATEGORY_NAME
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: CATEGORY_ID
    type: NUMBER
    nullable: false
    default: "\"OT\".\"ISEQ$$_77197\".nextval"
    comment: ""
  indexes: []
  constraints:
  - name: SYS_C0011002
    type: PRIMARY KEY
    def: PRIMARY KEY (CATEGORY_ID)
    table: OT.PRODUCT_CATEGORIES
    referencedTable: ""
    columns:
    - CATEGORY_ID
    referencedColumns: []
    comment: ""
  triggers: []
  def: ""
- name: OT.REGIONS
  type: TABLE
  comment: ""
  columns:
  - name: REGION_NAME
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: REGION_ID
    type: NUMBER
    nullable: false
    default: "\"OT\".\"ISEQ$$_77183\".nextval"
    comment: ""
  indexes: []
  constraints:
  - name: SYS_C0010980
    type: PRIMARY KEY
    def: PRIMARY KEY (REGION_ID)
    table: OT.REGIONS
    referencedTable: ""
    columns:
    - REGION_ID
    referencedColumns: []
    comment: ""
  triggers: []
  def: ""
- name: OT.CONTACTS
  type: TABLE
  comment: ""
  columns:
  - name: PHONE
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  - name: CUSTOMER_ID
    type: NUMBER
    nullable: true
    default: null
    comment: ""
  - name: FIRST_NAME
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: CONTACT_ID
    type: NUMBER
    nullable: false
    default: "\"OT\".\"ISEQ$$_77206\".nextval"
    comment: ""
  - name: LAST_NAME
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: EMAIL
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  indexes: []
  constraints:
  - name: SYS_C0011015
    type: PRIMARY KEY
    def: PRIMARY KEY (CONTACT_ID)
    table: OT.CONTACTS
    referencedTable: ""
    columns:
    - CONTACT_ID
    referencedColumns: []
    comment: ""
  - name: FK_CONTACTS_CUSTOMERS
    type: FOREIGN KEY
    def: FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
    table: OT.CONTACTS
    referencedTable: CUSTOMERS
    columns:
    - CUSTOMER_ID
    referencedColumns:
    - CUSTOMER_ID
    comment: ""
  triggers: []
  def: ""
- name: OT.LOCATIONS
  type: TABLE
  comment: ""
  columns:
  - name: LOCATION_ID
    type: NUMBER
    nullable: false
    default: "\"OT\".\"ISEQ$$_77188\".nextval"
    comment: ""
  - name: CITY
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  - name: STATE
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  - name: COUNTRY_ID
    type: CHAR
    nullable: true
    default: null
    comment: ""
  - name: ADDRESS
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: POSTAL_CODE
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  indexes: []
  constraints:
  - name: SYS_C0010986
    type: PRIMARY KEY
    def: PRIMARY KEY (LOCATION_ID)
    table: OT.LOCATIONS
    referencedTable: ""
    columns:
    - LOCATION_ID
    referencedColumns: []
    comment: ""
  - name: FK_LOCATIONS_COUNTRIES
    type: FOREIGN KEY
    def: FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (COUNTRY_ID)
    table: OT.LOCATIONS
    referencedTable: COUNTRIES
    columns:
    - COUNTRY_ID
    referencedColumns:
    - COUNTRY_ID
    comment: ""
  triggers: []
  def: ""
- name: OT.EMPLOYEES
  type: TABLE
  comment: This is a table for Employee
  columns:
  - name: EMAIL
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: JOB_TITLE
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: LAST_NAME
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: EMPLOYEE_ID
    type: NUMBER
    nullable: false
    default: "\"OT\".\"ISEQ$$_77194\".nextval"
    comment: ""
  - name: PHONE
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: FIRST_NAME
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: HIRE_DATE
    type: DATE
    nullable: false
    default: null
    comment: ""
  - name: MANAGER_ID
    type: NUMBER
    nullable: true
    default: null
    comment: ""
  indexes: []
  constraints:
  - name: SYS_C0010998
    type: PRIMARY KEY
    def: PRIMARY KEY (EMPLOYEE_ID)
    table: OT.EMPLOYEES
    referencedTable: ""
    columns:
    - EMPLOYEE_ID
    referencedColumns: []
    comment: ""
  - name: FK_EMPLOYEES_MANAGER
    type: FOREIGN KEY
    def: FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
    table: OT.EMPLOYEES
    referencedTable: EMPLOYEES
    columns:
    - MANAGER_ID
    referencedColumns:
    - EMPLOYEE_ID
    comment: ""
  triggers: []
  def: ""
- name: OT.INVENTORIES
  type: TABLE
  comment: ""
  columns:
  - name: PRODUCT_ID
    type: NUMBER
    nullable: false
    default: null
    comment: ""
  - name: QUANTITY
    type: NUMBER
    nullable: false
    default: null
    comment: ""
  - name: WAREHOUSE_ID
    type: NUMBER
    nullable: false
    default: null
    comment: ""
  indexes: []
  constraints:
  - name: PK_INVENTORIES
    type: PRIMARY KEY
    def: PRIMARY KEY (PRODUCT_ID, WAREHOUSE_ID)
    table: OT.INVENTORIES
    referencedTable: ""
    columns:
    - PRODUCT_ID
    - WAREHOUSE_ID
    referencedColumns: []
    comment: ""
  - name: FK_INVENTORIES_PRODUCTS
    type: FOREIGN KEY
    def: FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
    table: OT.INVENTORIES
    referencedTable: PRODUCTS
    columns:
    - PRODUCT_ID
    referencedColumns:
    - PRODUCT_ID
    comment: ""
  - name: FK_INVENTORIES_WAREHOUSES
    type: FOREIGN KEY
    def: FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES (WAREHOUSE_ID)
    table: OT.INVENTORIES
    referencedTable: WAREHOUSES
    columns:
    - WAREHOUSE_ID
    referencedColumns:
    - WAREHOUSE_ID
    comment: ""
  triggers: []
  def: ""
- name: OT.EMPLOYEE_VIEW
  type: VIEW
  comment: ""
  columns:
  - name: FULL_NAME
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  - name: YOS
    type: NUMBER
    nullable: true
    default: null
    comment: ""
  - name: EMPLOYEE_ID
    type: NUMBER
    nullable: false
    default: null
    comment: ""
  indexes: []
  constraints: []
  triggers: []
  def: |-
    
      CREATE OR REPLACE FORCE EDITIONABLE VIEW "OT"."EMPLOYEE_VIEW" ("EMPLOYEE_ID", "FULL_NAME", "YOS") AS 
      SELECT
        employee_id,
        first_name || ' ' || last_name full_name,
        FLOOR( months_between( CURRENT_DATE, hire_date )/ 12 ) yos
    FROM
        employees
  referencedTables:
  - employees
- name: OT.AUDITS
  type: TABLE
  comment: ""
  columns:
  - name: BY_USER
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  - name: TRANSACTION_NAME
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  - name: TABLE_NAME
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  - name: TRANSACTION_DATE
    type: DATE
    nullable: true
    default: null
    comment: ""
  - name: AUDIT_ID
    type: NUMBER
    nullable: false
    default: "\"OT\".\"ISEQ$$_77217\".nextval"
    comment: ""
  indexes: []
  constraints:
  - name: SYS_C0011035
    type: PRIMARY KEY
    def: PRIMARY KEY (AUDIT_ID)
    table: OT.AUDITS
    referencedTable: ""
    columns:
    - AUDIT_ID
    referencedColumns: []
    comment: ""
  triggers: []
  def: ""
- name: OT.PRODUCTS
  type: TABLE
  comment: ""
  columns:
  - name: CATEGORY_ID
    type: NUMBER
    nullable: false
    default: null
    comment: ""
  - name: DESCRIPTION
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  - name: PRODUCT_NAME
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: STANDARD_COST
    type: NUMBER
    nullable: true
    default: null
    comment: ""
  - name: LIST_PRICE
    type: NUMBER
    nullable: true
    default: null
    comment: ""
  - name: PRODUCT_ID
    type: NUMBER
    nullable: false
    default: "\"OT\".\"ISEQ$$_77200\".nextval"
    comment: ""
  indexes: []
  constraints:
  - name: SYS_C0011006
    type: PRIMARY KEY
    def: PRIMARY KEY (PRODUCT_ID)
    table: OT.PRODUCTS
    referencedTable: ""
    columns:
    - PRODUCT_ID
    referencedColumns: []
    comment: ""
  - name: FK_PRODUCTS_CATEGORIES
    type: FOREIGN KEY
    def: FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORIES (CATEGORY_ID)
    table: OT.PRODUCTS
    referencedTable: PRODUCT_CATEGORIES
    columns:
    - CATEGORY_ID
    referencedColumns:
    - CATEGORY_ID
    comment: ""
  triggers: []
  def: ""
- name: OT.CUSTOMERS
  type: TABLE
  comment: ""
  columns:
  - name: ADDRESS
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  - name: CUSTOMER_ID
    type: NUMBER
    nullable: false
    default: "\"OT\".\"ISEQ$$_77203\".nextval"
    comment: ""
  - name: CREDIT_LIMIT
    type: NUMBER
    nullable: true
    default: null
    comment: ""
  - name: WEBSITE
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  - name: NAME
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  indexes: []
  constraints:
  - name: SYS_C0011010
    type: PRIMARY KEY
    def: PRIMARY KEY (CUSTOMER_ID)
    table: OT.CUSTOMERS
    referencedTable: ""
    columns:
    - CUSTOMER_ID
    referencedColumns: []
    comment: ""
  triggers: []
  def: ""
- name: OT.ORDERS
  type: TABLE
  comment: ""
  columns:
  - name: CUSTOMER_ID
    type: NUMBER
    nullable: false
    default: null
    comment: ""
  - name: STATUS
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: ORDER_DATE
    type: DATE
    nullable: false
    default: null
    comment: ""
  - name: ORDER_ID
    type: NUMBER
    nullable: false
    default: "\"OT\".\"ISEQ$$_77209\".nextval"
    comment: ""
  - name: SALESMAN_ID
    type: NUMBER
    nullable: true
    default: null
    comment: ""
  indexes: []
  constraints:
  - name: SYS_C0011021
    type: PRIMARY KEY
    def: PRIMARY KEY (ORDER_ID)
    table: OT.ORDERS
    referencedTable: ""
    columns:
    - ORDER_ID
    referencedColumns: []
    comment: ""
  - name: FK_ORDERS_CUSTOMERS
    type: FOREIGN KEY
    def: FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
    table: OT.ORDERS
    referencedTable: CUSTOMERS
    columns:
    - CUSTOMER_ID
    referencedColumns:
    - CUSTOMER_ID
    comment: ""
  - name: FK_ORDERS_EMPLOYEES
    type: FOREIGN KEY
    def: FOREIGN KEY (SALESMAN_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
    table: OT.ORDERS
    referencedTable: EMPLOYEES
    columns:
    - SALESMAN_ID
    referencedColumns:
    - EMPLOYEE_ID
    comment: ""
  triggers: []
  def: ""
- name: OT.COUNTRIES
  type: TABLE
  comment: ""
  columns:
  - name: COUNTRY_NAME
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: REGION_ID
    type: NUMBER
    nullable: true
    default: null
    comment: ""
  - name: COUNTRY_ID
    type: CHAR
    nullable: false
    default: null
    comment: ""
  indexes: []
  constraints:
  - name: SYS_C0010982
    type: PRIMARY KEY
    def: PRIMARY KEY (COUNTRY_ID)
    table: OT.COUNTRIES
    referencedTable: ""
    columns:
    - COUNTRY_ID
    referencedColumns: []
    comment: ""
  - name: FK_COUNTRIES_REGIONS
    type: FOREIGN KEY
    def: FOREIGN KEY (REGION_ID) REFERENCES REGIONS (REGION_ID)
    table: OT.COUNTRIES
    referencedTable: REGIONS
    columns:
    - REGION_ID
    referencedColumns:
    - REGION_ID
    comment: ""
  triggers: []
  def: ""
relations:
- table: OT.WAREHOUSES
  columns:
  - LOCATION_ID
  parentTable: OT.LOCATIONS
  parentColumns:
  - LOCATION_ID
  def: FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (LOCATION_ID)
  virtual: false
- table: OT.ORDER_ITEMS
  columns:
  - ORDER_ID
  parentTable: OT.ORDERS
  parentColumns:
  - ORDER_ID
  def: FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
  virtual: false
- table: OT.ORDER_ITEMS
  columns:
  - PRODUCT_ID
  parentTable: OT.PRODUCTS
  parentColumns:
  - PRODUCT_ID
  def: FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
  virtual: false
- table: OT.CONTACTS
  columns:
  - CUSTOMER_ID
  parentTable: OT.CUSTOMERS
  parentColumns:
  - CUSTOMER_ID
  def: FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
  virtual: false
- table: OT.LOCATIONS
  columns:
  - COUNTRY_ID
  parentTable: OT.COUNTRIES
  parentColumns:
  - COUNTRY_ID
  def: FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRIES (COUNTRY_ID)
  virtual: false
- table: OT.EMPLOYEES
  columns:
  - MANAGER_ID
  parentTable: OT.EMPLOYEES
  parentColumns:
  - EMPLOYEE_ID
  def: FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
  virtual: false
- table: OT.INVENTORIES
  columns:
  - PRODUCT_ID
  parentTable: OT.PRODUCTS
  parentColumns:
  - PRODUCT_ID
  def: FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
  virtual: false
- table: OT.INVENTORIES
  columns:
  - WAREHOUSE_ID
  parentTable: OT.WAREHOUSES
  parentColumns:
  - WAREHOUSE_ID
  def: FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSES (WAREHOUSE_ID)
  virtual: false
- table: OT.PRODUCTS
  columns:
  - CATEGORY_ID
  parentTable: OT.PRODUCT_CATEGORIES
  parentColumns:
  - CATEGORY_ID
  def: FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORIES (CATEGORY_ID)
  virtual: false
- table: OT.ORDERS
  columns:
  - CUSTOMER_ID
  parentTable: OT.CUSTOMERS
  parentColumns:
  - CUSTOMER_ID
  def: FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
  virtual: false
- table: OT.ORDERS
  columns:
  - SALESMAN_ID
  parentTable: OT.EMPLOYEES
  parentColumns:
  - EMPLOYEE_ID
  def: FOREIGN KEY (SALESMAN_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID)
  virtual: false
- table: OT.COUNTRIES
  columns:
  - REGION_ID
  parentTable: OT.REGIONS
  parentColumns:
  - REGION_ID
  def: FOREIGN KEY (REGION_ID) REFERENCES REGIONS (REGION_ID)
  virtual: false
driver:
  name: oracle
  databaseVersion: 12.2.0.1.0
  meta:
    currentSchema: OT
    searchPaths:
    - OT
