name: AKASHY
desc: ""
tables:
- name: AASHISH.CUSTOMERS
  type: TABLE
  comment: ""
  columns:
  - name: ADDRESS
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  - name: CREDIT_LIMIT
    type: NUMBER
    nullable: true
    default: null
    comment: limit upto 100000
  - name: CUSTOMER_ID
    type: NUMBER
    nullable: false
    default: "\"AASHISH\".\"ISEQ$$_25630\".nextval"
    comment: ""
  - name: NAME
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: WEBSITE
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  indexes: []
  constraints:
  - name: SYS_C005988
    type: PRIMARY KEY
    def: PRIMARY KEY (CUSTOMER_ID)
    table: AASHISH.CUSTOMERS
    referencedTable: ""
    columns:
    - CUSTOMER_ID
    referencedColumns: []
    comment: ""
  triggers: []
  def: ""
- name: AASHISH.CUSTOMERS_VIEW
  type: VIEW
  comment: ""
  columns:
  - name: ADDRESS
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  - name: CUSTOMER_ID
    type: NUMBER
    nullable: false
    default: null
    comment: ""
  - name: NAME
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  - name: WEBSITE
    type: VARCHAR2
    nullable: true
    default: null
    comment: ""
  indexes: []
  constraints: []
  triggers: []
  def: |-
    SELECT
        ADDRESS,
        CUSTOMER_ID, NAME,
        WEBSITE 
    FROM AASHISH.CUSTOMERS
- name: AASHISH.PRODUCT_CATEGORIES
  type: TABLE
  comment: ""
  columns:
  - name: CATEGORY_ID
    type: NUMBER
    nullable: false
    default: "\"AASHISH\".\"ISEQ$$_25626\".nextval"
    comment: ""
  - name: CATEGORY_NAME
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  indexes: []
  constraints:
  - name: SYS_C005985
    type: PRIMARY KEY
    def: PRIMARY KEY (CATEGORY_ID)
    table: AASHISH.PRODUCT_CATEGORIES
    referencedTable: ""
    columns:
    - CATEGORY_ID
    referencedColumns: []
    comment: ""
  triggers: []
  def: ""
- name: AASHISH.REGIONS
  type: TABLE
  comment: ""
  columns:
  - name: REGION_ID
    type: NUMBER
    nullable: false
    default: "\"AASHISH\".\"ISEQ$$_25619\".nextval"
    comment: ""
  - name: REGION_NAME
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  indexes: []
  constraints:
  - name: SYS_C005982
    type: PRIMARY KEY
    def: PRIMARY KEY (REGION_ID)
    table: AASHISH.REGIONS
    referencedTable: ""
    columns:
    - REGION_ID
    referencedColumns: []
    comment: ""
  triggers: []
  def: ""
- name: AASHISH.REGIONS_VIEW
  type: VIEW
  comment: ""
  columns:
  - name: REGION_ID
    type: NUMBER
    nullable: false
    default: null
    comment: ""
  - name: REGION_NAME
    type: VARCHAR2
    nullable: false
    default: null
    comment: ""
  indexes: []
  constraints: []
  triggers: []
  def: SELECT "REGION_ID","REGION_NAME" FROM AASHISH.REGIONS
relations: []
driver:
  name: oracle
  databaseVersion: 19.0.0.0.0
  meta:
    currentSchema: AASHISH
    searchPaths:
    - AASHISH
