name: connect_test
desc: ""
tables:
- name: Chains.Sizes
  type: BASIC TABLE
  comment: ""
  columns:
  - name: ChainID
    type: int
    nullable: true
    default: null
    comment: ""
  - name: width
    type: decimal
    nullable: true
    default: null
    comment: ""
  indexes: []
  constraints: []
  triggers: []
  def: ""
relations: []
driver:
  name: sqlserver
  databaseVersion: |-
    Microsoft SQL Server 2019 (RTM-CU15) (KB5008996) - 15.0.4198.2 (X64) 
    	Jan 12 2022 22:30:08 
    	Copyright (C) 2019 Microsoft Corporation
    	Developer Edition (64-bit) on Linux (Ubuntu 20.04.3 LTS) <X64>
  meta: null
